spring:
  application:
    name: sentinel-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

server:
  tomcat:
    max-swallow-size: 2GB

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

logging:
  include-application-name: true
  level:
    com.seonghyeon.sentinelapi: INFO
    org.hibernate.orm.jdbc.bind: WARN
