replicaCount: 1

image:
  repository: "epfzja/sentinel-api"
  pullPolicy: IfNotPresent
  tag: "7e31fc0044f8d8d9feb43bf9c85a2eac7e606191"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  actuatorPort: 8081

secretName: sentinel-secret

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: actuator
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: actuator
  initialDelaySeconds: 30
  periodSeconds: 10

resources: {}

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi
  mountPath: /data
  storageRoot: /data/apps

nodeSelector: {}
tolerations: []
affinity: {}
