apiVersion: v1
kind: Secret
metadata:
    name: sentinel-secret
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:bF3XKCdgWnNu2dzi0AcT+DzWNE4AJptsyRQ9nJ6EDLB1NsEgYDQZrkrOi5oRVx84kW7IYMTVyigWWz1wndhLL526Mt5Gqzc=,iv:t6l0J9iASgbW8ZWCOcwm+Dmm7uanLzFNjkzD5sUHdiI=,tag:EQ4iMHBJqG2Pc3ByYW+4PA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:fchcoXJC7b4=,iv:BMQ8M9HjO367L3Ek6f6diNj6Gurt800Fv0xG1/x1IW0=,tag:jrRQbf1st7O3c+zNLsvk8w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:R1FRI+A8djA=,iv:6u7RLPs6ZrANi66/7y3lyx+Ad7Y5o+F/GcVWEyH29Sw=,tag:hgLbEY92fDHswCZ4C34QJw==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:UKfzeyBPzXSJXr0AkU0jSCYYo8YIuoAQNSnAtQxHr2/vKTqBFOTL3JvA+l/VhZotHHfQcGXqwY2JtqidmXLCjlAlWCpeEiO5MmIU7HKD2BMA,iv:RxpJtZEMVklmelrttTHJdnmT0phr60tY3v+4LRRRcPs=,tag:gar6PfSSg04y27CLVeHj9g==,type:str]
sops:
    age:
        - recipient: age1qzeg3ujug8tmcxesuje84t7rx85prcndzcjassl5j4axld0m543sjecg9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZndEZ1ltbzNXM0lXZjRY
            NFI1ajV0bzVURXplM2IzbDFYVXB3TW55blNVCkJRSnFjRnEyK3lnTndENzV1UmRP
            aytEdTJ2RkdtUW1weVRZRUVNa1daNFkKLS0tIEJxajN0OVdQd0c1RVpqd2hUUHNz
            M1dnS1hHZ2h3UmlBdi9DWDlpNW5URXMKmwHYM5GOaj5MbleODQJvkA3JrZq5/WPS
            aV7nQfbNi3kIRjKll+hqwIjf7TD1fPCgM3YgRz4QHbHH/qgHe2MP0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T03:52:03Z"
    mac: ENC[AES256_GCM,data:fA2IuDvhB4qVHMfXHq9vIyv21LyhWCJ+Z4xxNzTVazrYStunj3BkjmCyM5BGTs1AS5iDEXFvBe4lfWV/P26TRdo3RdhEeygpeBXE5Zjbxecp1Lk2hF5wdXxG7dzI2g0s9AeMsMkikD72aYILIDxwkbu3/1nM+s7005wclLmsFA0=,iv:+fee1UCninGBWM364X/q7Ia+pJW+pIEgfkJ2gyLWWA8=,tag:euPmNw9kfR9wU6DS6mL06g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
